version: '3.8'

services:
  # 1. PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: flash_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flashsale
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d flashsale"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Redis - Кэш и In-memory хранилище для Flash-Sale (LUA-скрипты)
  redis:
    image: redis:7-alpine
    container_name: flash_redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  # 3. Apache Kafka (KRaft mode, без Zookeeper для экономии ресурсов)
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: flash_kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      interval: 10s
      timeout: 5s
      retries: 3

  # 4. Elasticsearch
  elasticsearch:
    image: elasticsearch:9.5.3
    container_name: flash_elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      # Ограничиваем память, чтобы не повесить ноутбук (512 МБ)
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      interval: 10s
      timeout: 10s
      retries: 10

  # 5. Kafka UI - Графический интерфейс для просмотра топиков и сообщений Kafka
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: flash_kafka_ui
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka

volumes:
  postgres_data:
  elastic_data:
